### ISSUE TITLE
术语翻译: Adequatism

### ISSUE THREAD

**Issue by zhuyan166** [biomedontology/TermChinesetranslation#1]
来自于“Building Ontologies with Basic Formal Ontology"
定义：The view that the entities in any given domain should be taken seriously on their own terms (as contrasted with reductionism). The goal of adequatism is to do justice to all the different kinds of entities that exist in reality; see also General principles  of ontology design.

**Comment by yongqunh** [comment]
What are the Chinese translations of adequatism?
